name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
  upload_build_files:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Get artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  get_build_files:
    needs: upload_build_files
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: build