name: PR
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print_github_object:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "${{ toJSON(github) }}"